post:
  x-eov-operation-id: activateWorkflow
  x-eov-operation-handler: v1/handlers/workflows/workflows.handler
  tags:
    - Workflow
  summary: Activate a workflow
  description: Active a workflow.
  parameters:
    - $ref: '../schemas/parameters/workflowId.yml'
  requestBody:
    description: Optional parameters for workflow activation.
    required: false
    content:
      application/json:
        schema:
          type: object
          properties:
            versionId:
              type: string
              description: The specific version ID of the workflow to activate. If not provided, the current workflow version will be activated.
  responses:
    '200':
      description: Workflow object
      content:
        application/json:
          schema:
            $ref: '../schemas/workflow.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '404':
      $ref: '../../../../shared/spec/responses/notFound.yml'
