post:
  x-eov-operation-id: activateWorkflow
  x-eov-operation-handler: v1/handlers/workflows/workflows.handler
  tags:
    - Workflow
  summary: Activate a workflow
  description: Active a workflow.
  parameters:
    - $ref: '../schemas/parameters/workflowId.yml'
  requestBody:
    description: Optional version ID to activate
    required: false
    content:
      application/json:
        schema:
          type: object
          properties:
            versionId:
              type: string
              description: Version ID from workflow history to activate. If not provided, the current version will be activated.
              example: '550e8400-e29b-41d4-a716-446655440000'
  responses:
    '200':
      description: Workflow object
      content:
        application/json:
          schema:
            $ref: '../schemas/workflow.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '404':
      $ref: '../../../../shared/spec/responses/notFound.yml'
