name: Test Postgres and MySQL schemas

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - packages/cli/src/databases/**
      - packages/cli/src/modules/*/database/**
      - packages/cli/src/modules/**/*.entity.ts
      - packages/cli/src/modules/**/*.repository.ts
      - packages/cli/test/integration/**
      - packages/cli/test/shared/db/**
      - packages/@n8n/db/**
      - packages/cli/**/__tests__/**
      - .github/workflows/ci-postgres-mysql.yml
      - .github/docker-compose.yml
  pull_request_review:
    types: [submitted]

concurrency:
  group: db-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

env:
  NODE_OPTIONS: '--max-old-space-size=3072'

jobs:
  build:
    name: Install & Build
    runs-on: blacksmith-2vcpu-ubuntu-2204
    if: github.event_name != 'pull_request_review' || startsWith(github.event.pull_request.base.ref, 'release/')
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup and Build
        uses: n8n-io/n8n/.github/actions/setup-nodejs-blacksmith@f5fbbbe0a28a886451c886cac6b49192a39b0eea # v1.104.1

  mysql:
    name: MySQL 8.4
    needs: build
    runs-on: blacksmith-2vcpu-ubuntu-2204
    timeout-minutes: 20
    env:
      DB_MYSQLDB_PASSWORD: password
      DB_MYSQLDB_POOL_SIZE: 1
      DB_MYSQLDB_CONNECTION_TIMEOUT: 120000
      DB_MYSQLDB_ACQUIRE_TIMEOUT: 120000
      DB_MYSQLDB_TIMEOUT: 120000
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup and Build
        uses: n8n-io/n8n/.github/actions/setup-nodejs-blacksmith@f5fbbbe0a28a886451c886cac6b49192a39b0eea # v1.104.1

      - name: Start MySQL
        uses: isbang/compose-action@802a148945af6399a338c7906c267331b39a71af # v2.0.0
        with:
          compose-file: ./.github/docker-compose.yml
          services: mysql-8.4

      - name: Test MySQL
        working-directory: packages/cli
        run: pnpm test:mysql --testTimeout 120000

      - name: Print logs
        run: cat .github/mysql/log/general.log
