name: Debug Flaky E2E Test (Temporary Push Trigger)

# Trigger automatically ONLY on pushes to your specific development branch
on:
  push:
    branches:
      - CAT-754-flaky-test-workflow

jobs:
  debug-test:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    timeout-minutes: 60

    steps:
      # Checkout the code from the commit that triggered the push
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Cache build artifacts
        id: cache-build-artifacts
        uses: useblacksmith/cache@v5
        with:
          path: |
            /home/runner/.cache/Cypress
            ./packages/**/dist
          key: ${{ github.ref }}-${{ github.sha }}-debug-build
          restore-keys: |
            ${{ github.ref }}-debug-build-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        run: pnpm build

      - name: Cypress install
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        working-directory: cypress
        run: pnpm cypress:install

      - name: Run Flaky Debug Command via ENV
        env:
          E2E_DEBUG_FILTER: "maps paired input and output items based on selected input node"
          E2E_DEBUG_COUNT: 50
        run: pnpm run debug:flaky:e2e $E2E_DEBUG_FILTER $E2E_DEBUG_COUNT